version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-echo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ldz4m5mquwus"
s3_prefix = "hello-echo"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
